# Generated by Django 4.1.7 on 2023-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_country_manufacturer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, default='category-placeholder.jpeg', upload_to='categories/'),
        ),
    ]
