# Generated by Django 3.2.18 on 2023-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_manufacturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
