# Generated by Django 4.1.7 on 2023-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_country_manufacturer_product_and_more'),
        ('cart', '0002_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
    ]
